const express = require("express");
const router = express.Router();

const requestRouter = require("./routers/request.router");
const currencyRouter = require("./routers/currency.router");
const reelRouter = require("./routers/reel.router");
const commentRouter = require("./routers/comment.router");
const postRouter = require("./routers/post.router");
const termsRouter = require("./routers/terms.router");
const reportRouter = require("./routers/report.router");
const image3dRouter = require("./routers/image3d.router");
const unitRouter = require("./routers/unit.router");
const rateRouter = require("./routers/rate.router");
const likeReelRouter = require("./routers/likeReel.router");
const favoritePostRouter = require("./routers/favoritePost.router");
const walletRouter = require("./routers/wallet.router");
const bankRouter = require("./routers/bank.router");
const transactionRouter = require("./routers/transaction.router");
const bookingRouter = require("./routers/booking.router");
const adminRouter = require("./routers/admin.router");
const userRouter = require("./routers/user.router");
const fcmRouter = require("./routers/fcm.router");
const notificationRouter = require("./routers/notification.router");

router.use("/admin", adminRouter);
router.use("/request", requestRouter);
router.use("/currency", currencyRouter);
router.use("/reel", reelRouter);
router.use("/comment", commentRouter);
router.use("/post", postRouter);
router.use("/terms", termsRouter);
router.use("/report", reportRouter);
router.use("/image3d", image3dRouter);
router.use("/unit", unitRouter);
router.use("/rate", rateRouter);
router.use("/likeReel", likeReelRouter);
router.use("/favoritePost", favoritePostRouter);
router.use("/wallet", walletRouter);
router.use("/bank", bankRouter);
router.use("/transaction", transactionRouter);
router.use("/booking", bookingRouter);
router.use("/user", userRouter);
router.use("/fcm", fcmRouter);
router.use("/notification", notificationRouter);

module.exports = router;
