const express = require("express");
const publicRouter = express.Router();
const postController = require("../controllers/post.controller");
const termsController = require("../controllers/terms.controller");
const image3dController = require("../controllers/image3d.controller");
const likeReelController = require("../controllers/likeReel.controller");
const favoritePostController = require("../controllers/favoritePost.controller");
const reelController = require("../controllers/reel.controller");
const commentController = require("../controllers/comment.controller");
const unitController = require("../controllers/unit.controller");
const rateController = require("../controllers/rate.controller");
const bookingController = require("../controllers/booking.controller");
const countryController = require("../controllers/country.controller");
const roles = require("../../helpers/roles");

publicRouter.post("/booking/all", bookingController.getAllData);
publicRouter.post("/post", postController.getAllData);
publicRouter.get("/get-time-zone", countryController.getTimeZone);
publicRouter.post("/post/map", postController.getAllDataMap);
publicRouter.post("/post/filter-post", postController.getAllDataFilterPost);
publicRouter.post("/post/:id", postController.findById);
publicRouter.post("/image3d/all", image3dController.getAllData);
publicRouter.get("/image3d/:id", image3dController.findById);
publicRouter.post("/like-reel/all", likeReelController.getAllData);
publicRouter.get("/like-reel/:id", likeReelController.findById);
publicRouter.post("/terms/all", termsController.getAllData);
publicRouter.get("/terms/:id", termsController.findById);
publicRouter.post("/favorite-post/all", favoritePostController.getAllData);
publicRouter.get("/favorite-post/:id", favoritePostController.findById);
publicRouter.post("/reel/all", reelController.getAllData);
publicRouter.get("/reel/:id", reelController.findById);
publicRouter.post("/comment/all", commentController.getAllData);
publicRouter.get("/unit/:id", unitController.findById);
publicRouter.post("/unit/near-units-to-posts", unitController.findNearUnitsToPosts);
publicRouter.post("/unit/near-units", unitController.findNearUnits);
publicRouter.post("/unit/get-coordinates", unitController.getCoordinates);

publicRouter.post("/rate/all-with-comments", rateController.getAllDataWithComments);

module.exports = publicRouter;